modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory (24 is current forge version)
issueTrackerURL="http://drf" #optional
[[mods]] #mandatory
modId="drf" #mandatory
version="${file.jarVersion}" #mandatory
displayName="DiningFurniture" #mandatory
updateJSONURL="http://drf" #optional
displayURL="http://drf" #optional
logoFile="drf.png" #optional
credits="DiningFurniture Mod" #optional
authors="DiningFurniture" #optional
description="Add Block DiningFurniture"
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.drf]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[25,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.drf]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"