// Date: 2016/10/05 23:41:16
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelIcecream extends ModelBase
{
  //fields
    ModelRenderer casebase;
    ModelRenderer casecupsid4;
    ModelRenderer casecupsid3;
    ModelRenderer caseporl;
    ModelRenderer casecupbase;
    ModelRenderer casecupsid2;
    ModelRenderer casecupsid1;
    ModelRenderer Ice1;
  
  public ModelIcecream()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      casebase = new ModelRenderer(this, 0, 0);
      casebase.addBox(-4F, 0F, -4F, 8, 1, 8);
      casebase.setRotationPoint(0F, 23F, 0F);
      casebase.setTextureSize(64, 32);
      casebase.mirror = true;
      setRotation(casebase, 0F, 0F, 0F);
      casecupsid4 = new ModelRenderer(this, 42, 0);
      casecupsid4.addBox(-5F, -12F, -6F, 10, 4, 1);
      casecupsid4.setRotationPoint(0F, 23F, 0F);
      casecupsid4.setTextureSize(64, 32);
      casecupsid4.mirror = true;
      setRotation(casecupsid4, 0F, -1.570796F, 0F);
      casecupsid3 = new ModelRenderer(this, 42, 0);
      casecupsid3.addBox(-5F, -12F, -6F, 10, 4, 1);
      casecupsid3.setRotationPoint(0F, 23F, 0F);
      casecupsid3.setTextureSize(64, 32);
      casecupsid3.mirror = true;
      setRotation(casecupsid3, 0F, 1.570796F, 0F);
      caseporl = new ModelRenderer(this, 32, 0);
      caseporl.addBox(-1F, -8F, -1F, 2, 8, 2);
      caseporl.setRotationPoint(0F, 23F, 0F);
      caseporl.setTextureSize(64, 32);
      caseporl.mirror = true;
      setRotation(caseporl, 0F, 0F, 0F);
      casecupbase = new ModelRenderer(this, 0, 10);
      casecupbase.addBox(-5F, -9F, -5F, 10, 1, 10);
      casecupbase.setRotationPoint(0F, 23F, 0F);
      casecupbase.setTextureSize(64, 32);
      casecupbase.mirror = true;
      setRotation(casecupbase, 0F, 0F, 0F);
      casecupsid2 = new ModelRenderer(this, 42, 0);
      casecupsid2.addBox(-5F, -12F, -6F, 10, 4, 1);
      casecupsid2.setRotationPoint(0F, 23F, 0F);
      casecupsid2.setTextureSize(64, 32);
      casecupsid2.mirror = true;
      setRotation(casecupsid2, 0F, 0F, 0F);
      casecupsid1 = new ModelRenderer(this, 42, 0);
      casecupsid1.addBox(-5F, -12F, 5F, 10, 4, 1);
      casecupsid1.setRotationPoint(0F, 23F, 0F);
      casecupsid1.setTextureSize(64, 32);
      casecupsid1.mirror = true;
      setRotation(casecupsid1, 0F, 0F, 0F);
      Ice1 = new ModelRenderer(this, 32, 18);
      Ice1.addBox(-4F, -15F, -4F, 8, 6, 8);
      Ice1.setRotationPoint(0F, 23F, 0F);
      Ice1.setTextureSize(64, 32);
      Ice1.mirror = true;
      setRotation(Ice1, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    casebase.render(f5);
    casecupsid4.render(f5);
    casecupsid3.render(f5);
    caseporl.render(f5);
    casecupbase.render(f5);
    casecupsid2.render(f5);
    casecupsid1.render(f5);
    Ice1.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
